/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutomationSettings {
  'autoClickEnabled' : boolean,
  'waitTime' : bigint,
  'targetUrl' : string,
}
export interface LogEntry {
  'profileId' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
}
export interface Profile {
  'id' : string,
  'isSelected' : boolean,
  'name' : string,
}
export interface ProfileStatus { 'status' : string, 'profileId' : string }
export interface _SERVICE {
  'getLogs' : ActorMethod<[], Array<LogEntry>>,
  'getProfileStatuses' : ActorMethod<[], Array<ProfileStatus>>,
  'getProfiles' : ActorMethod<[], Array<Profile>>,
  'initializeProfiles' : ActorMethod<[], undefined>,
  'isOperationRunning' : ActorMethod<[], boolean>,
  'startQueue' : ActorMethod<[], undefined>,
  'stopQueue' : ActorMethod<[], undefined>,
  'toggleProfileSelection' : ActorMethod<[string], undefined>,
  'updateSettings' : ActorMethod<[AutomationSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];