/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LogEntry = IDL.Record({
  'profileId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ProfileStatus = IDL.Record({
  'status' : IDL.Text,
  'profileId' : IDL.Text,
});
export const Profile = IDL.Record({
  'id' : IDL.Text,
  'isSelected' : IDL.Bool,
  'name' : IDL.Text,
});
export const AutomationSettings = IDL.Record({
  'autoClickEnabled' : IDL.Bool,
  'waitTime' : IDL.Nat,
  'targetUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getProfileStatuses' : IDL.Func([], [IDL.Vec(ProfileStatus)], ['query']),
  'getProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'initializeProfiles' : IDL.Func([], [], []),
  'isOperationRunning' : IDL.Func([], [IDL.Bool], ['query']),
  'startQueue' : IDL.Func([], [], []),
  'stopQueue' : IDL.Func([], [], []),
  'toggleProfileSelection' : IDL.Func([IDL.Text], [], []),
  'updateSettings' : IDL.Func([AutomationSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LogEntry = IDL.Record({
    'profileId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ProfileStatus = IDL.Record({
    'status' : IDL.Text,
    'profileId' : IDL.Text,
  });
  const Profile = IDL.Record({
    'id' : IDL.Text,
    'isSelected' : IDL.Bool,
    'name' : IDL.Text,
  });
  const AutomationSettings = IDL.Record({
    'autoClickEnabled' : IDL.Bool,
    'waitTime' : IDL.Nat,
    'targetUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getProfileStatuses' : IDL.Func([], [IDL.Vec(ProfileStatus)], ['query']),
    'getProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'initializeProfiles' : IDL.Func([], [], []),
    'isOperationRunning' : IDL.Func([], [IDL.Bool], ['query']),
    'startQueue' : IDL.Func([], [], []),
    'stopQueue' : IDL.Func([], [], []),
    'toggleProfileSelection' : IDL.Func([IDL.Text], [], []),
    'updateSettings' : IDL.Func([AutomationSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };